### PR TITLE
Remove TaskList::Item#source

### PR DESCRIPTION
**Pull request by aroben**
This isn't used at all in the github.com Rails app.

/cc @mtodd

### CODE REVIEW

**Comment by aroben** [comment]
@mtodd How's this look to you?

**Comment by mtodd** [comment]
@aroben looks good to me! Need to get this merged in soon?

On Thursday, June 18, 2015, Adam Roben <notifications@github.com> wrote:

> @mtodd <https://github.com/mtodd> How's this look to you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/github/task_list/pull/59#issuecomment-113161766>.
>


-- 
Matt Todd
GitHub, Inc
www.github.com
cell: 404-314-2612
blog: maraby.org

**Comment by aroben** [comment]
No rush, just wanted to ping since I hadn't heard back from you yet.

**Comment by mtodd** [comment]
@aroben :+1: OOO this week so it'll likely be next week before I get back to this. Thanks for the bump, though!

**Pull request closed without merging**
